---
- name: Configure OpenResty sites with Let's Encrypt certificates
  hosts: all
  become: true
  vars:
    sites_dir: /etc/openresty/sites-enabled
    certbot_packages_debian:
      - certbot
    certbot_packages_redhat:
      - certbot


  tasks:
    - name: Ensure site directory exists
      ansible.builtin.file:
        path: "{{ sites_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Install certbot and nginx plugin on Debian/Ubuntu
      ansible.builtin.apt:
        name: "{{ certbot_packages_debian }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install certbot and nginx plugin on RedHat/CentOS
      ansible.builtin.yum:
        name: "{{ certbot_packages_redhat }}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Configure virtualhosts
      ansible.builtin.include_tasks: site_setup.yml
      loop: "{{ vhosts }}"
      loop_control:
        loop_var: vhost

  handlers:
    - name: Reload openresty
      ansible.builtin.service:
        name: openresty
        state: reloaded

    - name: Restart openresty
      ansible.builtin.service:
        name: openresty
        state: restarted
