---
- name: Ensure webroot directory exists
  ansible.builtin.file:
    path: "{{ vhost.webroot }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Check if certificate already exists for {{ vhost.server_name }}
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ vhost.server_name }}/fullchain.pem"
  register: cert_status

- name: Deploy temporary ACME vhost
  template:
    src: vhost_acme.j2
    dest: "{{ sites_dir }}/{{ vhost.server_name }}.conf"
  when: not cert_status.stat.exists
  notify: Reload openresty

- name: Wait for OpenResty to reload
  ansible.builtin.pause:
    seconds: 5
  when: not cert_status.stat.exists

- name: Obtain certificate via certbot (first install)
  command: >
    certbot certonly --webroot -w {{ vhost.webroot }}
    --non-interactive --agree-tos
    --email {{ vhost.email }} -d {{ vhost.server_name }}
  when: not cert_status.stat.exists

- name: Deploy final HTTPS vhost config
  template:
    src: vhost.j2
    dest: "{{ sites_dir }}/{{ vhost.server_name }}.conf"
    mode: '0644'
  notify: Reload openresty